# Generated by Django 3.0.6 on 2020-05-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Needer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('immunocompromised', models.BooleanField(default=False)),
                ('mask_collection_preference', models.CharField(max_length=10)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('profile_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
